replicaCount: 1
image:
  repository: harbor.pintobean.xyz/aspenmesh-demo-site/frontend
  pullPolicy: Always
  tag: "0.1.0"
namespace: "frontend"
nameOverride: "frontend"
fullnameOverride: "frontend"
containerPort: 8080
container:
  name: "server"
serviceAccount:
  create: false
  annotations: {}
  name: ""
livenessProbe:
  initialDelay: 10
  httpGet:
    path: "/_healthz"
    port: 8080
    httpHeaders:
    - name: "Cookie"
      value: "shop_session-id=x-readiness-probe"
readinessProbe:
  initialDelay: 10
  httpGet:
    path: "/_healthz"
    port: 8080
    httpHeaders:
    - name: "Cookie"
      value: "shop_session-id=x-readiness-probe"
env:
- name: PORT
  value: "8080"
- name: PRODUCT_CATALOG_SERVICE_ADDR
  value: "productcatalogservice.product-catalog:3550"
- name: CURRENCY_SERVICE_ADDR
  value: "currencyservice.payments:7000"
- name: CART_SERVICE_ADDR
  value: "cartservice.shopping-cart:7070"
- name: RECOMMENDATION_SERVICE_ADDR
  value: "recommendationservice.recommendations:8080"
- name: SHIPPING_SERVICE_ADDR
  value: "shippingservice.fulfillment:50051"
- name: CHECKOUT_SERVICE_ADDR
  value: "checkoutservice.checkout:5050"
- name: AD_SERVICE_ADDR
  value: "adservice.ad-engine:9555"
- name: ENV_PLATFORM 
  value: "aws"
- name: DISABLE_TRACING
  value: "1"
- name: DISABLE_PROFILER
  value: "1"
- name: CYMBAL_BRANDING
  value: "false"
resources: 
  requests:
    cpu: 100m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80
service:
  type: ClusterIP
  port: 8080
  targetPort: 8080
  name: http