---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "otelagent.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "otelagent.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "otelagent.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "otelagent.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "otelagent.serviceAccountName" . }}
      containers:
        - name: {{ default .Chart.Name .Values.otelagent,container.name }}
          image: "{{ .Values.otelagent.image.repository }}:{{ .Values.otelagent.image.tag | default .Chart.AppVersion }}"
          command:
            {{- toYaml .Values.otelagent.container.command . | nindent 12 }}
          volumeMounts:
            {{- toYaml .Values.otelagent.container.volumeMounts . | nindent 12 }}
          ports:
            {{- toYaml .Values.otelagent.container.ports . | nindent 12 }}
      volumes:
        {{- toYaml .Values.otelagent.volumes . | nindent 8 }}