apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "boutiquedb.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "boutiquedb.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "boutiquedb.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "boutiquedb.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "boutiquedb.serviceAccountName" . }}
      containers:
        - name: {{ default .Chart.Name .Values.container.name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.containerPort }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            {{- toYaml .Values.env | nindent 12 }}